#!/bin/bash

# This script sets up the workspace
# and switches the env variables.

function help() {
    echo "Usage: $0 <WORKSPACE DIR> <APP DIR>"
    echo ""
    echo "Sets up the workspace in the WORKSPACE DIR (created if needed)"
    echo "and decompiles the electron.js application installed at the APP DIR"
    echo ""
    echo "Workspace will have a default directory structure and a git repo"
    echo "initialized. These are described below:"
    echo ""
    echo "\`patches\` directory contains the set of patches generated by the CLI."
    echo "\`src\` directory is a workspace for the modified sources."
    echo "\`.vkmeta\` file is a workspace meta file that contains the CLI version."
}

# Print help if no
# arguments are provided at all!
if [[ $# == 0 ]]; then
    help
    return 1
fi

export SCRIPTS_DIR=`dirname $0`
WORKSPACE_DIR="${1:?"Error: Missing workspace directory argument"}"
APP_DIR="${2:?"Error: Missing application directory argument"}"

# Convert to the absolute paths
WORKSPACE_DIR=`realpath $WORKSPACE_DIR`
APP_DIR=`realpath $APP_DIR`

# Create the workspace directory
# if not yet created.
[[ ! -d $WORKSPACE_DIR ]] && (mkdir $WORKSPACE_DIR || return 1)

export VKPATCHER_WORKSPACE=$WORKSPACE_DIR && echo "Switched the current workspace to $WORKSPACE_DIR"

# If there was a workspace there
# then just switch the environment var.
META_FILE="$WORKSPACE_DIR/.vkmeta"
[[ -f $META_FILE ]] && return 0

# Write the current version to the meta file
echo "$($SCRIPTS_DIR/get_version.sh cli)" > $META_FILE

# Decompile the sources
SRC_DIR="$WORKSPACE_DIR/src"
$SCRIPTS_DIR/decompile_sources.sh "$APP_DIR" "$SRC_DIR" || return 1

# Initialize separated git repos.
# Src repo is needed for modifications tracking to build diffs.
# Workspace repo should be used for publishing patches.
git init "$SRC_DIR"
git init "$WORKSPACE_DIR"

# Clone gitignore file
cp "$SCRIPTS_DIR/../.gitignore" "$WORKSPACE_DIR"

# Create patches directory
mkdir "$WORKSPACE_DIR/patches"

# Make a first commit
cd "$SRC_DIR" && git add . && git commit -m "Decompiled sources"

# Tree the directory
tree "$WORKSPACE_DIR"
